export { default as ArrowBackIos } from './arrow_back_ios.svg';
export { default as Visibility } from './visibility.svg';
export { default as VisibilityOff } from './visibility_off.svg';
export { default as Info } from './info.svg';
export { default as Warning } from './warning.svg';
export { default as CheckCircle } from './check_circle.svg';
export { default as AccountCircle } from './account_circle.svg';
export { default as Login } from './login.svg';
export { default as Logout } from './logout.svg';
export { default as Person } from './person.svg';
export { default as Menu } from './menu.svg';
export { default as Grade } from './grade.svg';
export { default as KeyboardDoubleArrowLeft } from './keyboard_double_arrow_left.svg';
export { default as KeyboardDoubleArrowRight } from './keyboard_double_arrow_right.svg';
export { default as KeyboardArrowRight } from './keyboard_arrow_right.svg';
export { default as KeyboardArrowLeft } from './keyboard_arrow_left.svg';

export { default as Logo } from './logo_base.svg';
export { default as Logo_w } from './logo_white.svg';
